languageCode = "en-us"
ignoreFiles = [ "\\.files/README.md$",  "content/intermediate/260_weave_flux/app.files/"]
defaultContentLanguage = "en"
title = "Amazon EKS Workshop"
theme = "learn"
uglyurls = false
# googleAnalytics = "UA-44634850-4"
sectionPagesMenu = "main"
relativeURLs = true

[blackfriday]
hrefTargetBlank = true

[params]
#editURL = "https://github.com/aws-samples/eks-workshop/edit/main/content/"
themeVariant = "mine"
showVisitedLinks = false
author = "Brent Langston"
description = "Amazon EKS Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=false
disableInlineCopyToClipBoard = true
ghrepo = "https://github.com/aws-samples/eks-workshop/"
branch = "main"
template_bucket = "eksworkshop.com"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "tango"


[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = true
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[services]
  [services.youtube]
    privacyEnhanced = true



#

[menu]
  [[menu.main]]
    identifier = "Prerequisites"
    name = "This is the Mu track"
    title = "Workshop using Mu"
    url = "/mu/"
    weight = -110

[[menu.shortcuts]]
name = "<i class='fas fa-chalkboard'></i> AWS Partner Workshops"
url = "https://awsworkshop.io"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-envelope'></i> Have questions?"
url = "mailto:bthomason@newrelic.com"
weight = 40


[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]
